# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:12.13-buster
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: sudo apt-get update -yq && sudo apt install -yq lftp pandoc gvfs emacs
      - run:
          name: Deploy to https://organice.200ok.ch
          command: ./bin/compile_and_upload.sh
      - run:
          name: Deploy documentation to https://organice.200ok.ch/documentation.html
          command: ./bin/compile_doc_and_upload.sh

  build:
    docker:
      - image: circleci/node:12.13-buster
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Javascript Dependencies
          command: yarn install --frozen-lockfile

      - run:
          name: Show Dependencies
          command: yarn list

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: eslint
          command: yarn eslint

      - run:
          name: prettier-eslint
          # Make the build output more useful by immediately showing full details of
          # any style violations.
          command: |
            yarn prettier-eslint --write
            GIT_PAGER= git diff
            git reset --hard HEAD
            yarn prettier-eslint --list-different

      - run: yarn test

  build-docs:
    docker:
      - image: circleci/node:12.13-buster
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Documentation Dependencies
          command: sudo apt-get update -yq && sudo apt install -yq pandoc emacs

      - run:
          name: Compile documentation
          command: ./bin/compile_doc.sh

  push-image:
    machine: true
    steps:
      - checkout
      # Build docker image and push it to DockerHub
      - run: docker build --rm=false -t ${DOCKER_HUB_USR}/organice:${CIRCLE_BUILD_NUM} .
      - run: docker login --username ${DOCKER_HUB_USR} --password ${DOCKER_HUB_PWD}
      - run: docker push ${DOCKER_HUB_USR}/organice:${CIRCLE_BUILD_NUM}
      # Re-assign latest tag to current build
      - run: docker tag ${DOCKER_HUB_USR}/organice:${CIRCLE_BUILD_NUM} ${DOCKER_HUB_USR}/organice:latest
      - run: docker push ${DOCKER_HUB_USR}/organice:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - build-docs
      - deploy:
          requires:
            - build
            - build-docs
          filters:
            branches:
              only: master
      - push-image:
          requires:
            - build # because of tests
            - build-docs
          filters:
            branches:
              only: master
