version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: cd examples/001-flutter_default_counter_app && flutter test
      - run: cd examples/002-form_validation_with_reactive_model && flutter test
      - run: cd examples/003-async_counter_app_with_injector && flutter test
      - run: cd examples/004-countdown_timer && flutter test
      - run: cd examples/005-double_async_counter_with_error && flutter test
      - run: cd examples/007-clean_architecture_dane_mackier_app && flutter test
      - run: cd examples/008-clean_architecture_firebase_login && flutter test
      - run: cd examples/010-clean_architecture__multi_counter_realtime_firebase && flutter test
      - run : cd states_rebuilder_package && flutter test --coverage
      - run: bash <(curl -s https://codecov.io/bash)