version: 2
jobs:
  build:
    docker:
      - image: clojure:openjdk-8-lein-2.9.3
    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run: lein test

      - run: lein bin

      - persist_to_workspace:
          root: target
          paths:
            - clojure-lsp

  release:
    docker:
      - image: circleci/golang:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/target
      - run: go get github.com/tcnksm/ghr
      - run: git fetch --tags
      - run: git --no-pager tag --list
      - run: echo ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $(git describe --tags) target/clojure-lsp
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $(git describe --tags) target/clojure-lsp

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /^release.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^release.*/
            branches:
              ignore: /.*/
