version: 2
jobs:
  build:
    docker:
      - image: nutti/blender_addon_ci:v1.0
    branches:
      only:
        - master
        - ci_testing
    steps:
      - checkout
      - run:
          name: Compress add-on as .zip file
          command: mkdir release && cd src && zip -r screencast_keys.zip screencast_keys && cd .. && mv src/screencast_keys.zip release
      - store_artifacts:
          path: release
          destination: screencast_keys