version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: go test -v -race -bench . ./...
      - run: GOARCH=386 go test github.com/libp2p/... || true