version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.5

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools
            pip install pytest twine wheel
            pip install -r requirements.txt -r optional-requirements.txt
            pip install https://github.com/shinmorino/qgate/raw/gh-pages/packages/0.2/qgate-0.2.2-cp37-cp37m-manylinux1_x86_64.whl
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: create a result directory
          command: mkdir -p test-reports/python

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest tests/ --junitxml=test-reports/python/junit.xml --add-backend qgate

      - run:
          name: twine check
          command: |
            . venv/bin/activate
            python setup.py build sdist bdist_wheel
            twine check dist/*

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  check_all:
    jobs:
      - build
