language: rust
rust:
  - nightly
before-install:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
install:
  - wasm-pack build lib/rvemu-wasm --target web
  - cargo build --release --manifest-path lib/rvemu-cli/Cargo.toml
script:
  - make test
