sudo: required
services:
  - docker

jobs:
  include:
    - stage: Install
      script: sudo apt-get update

    - stage: Docker
      script:
        - docker run --name openvinocont -t -d openvinoincluit/openvino:latest
        - docker exec openvinocont git clone https://github.com/incluit/OpenVino-For-SmartCity
        - docker exec openvinocont bash -c 'source /opt/intel/openvino/bin/setupvars.sh && cd /app/OpenVino-For-SmartCity && mkdir build && cd build && source /app/OpenVino-For-SmartCity/scripts/setupenv.sh && cmake .. && make'
        - docker exec openvinocont bash -c 'cd /app/OpenVino-For-SmartCity/build && build-wrapper-linux-x86-64 --out-dir bw-output make clean all'
        - docker exec openvinocont bash -c 'cd /app/OpenVino-For-SmartCity/build && sonar-scanner -Dsonar.projectKey=incluit_OpenVino-For-SmartCity -Dsonar.organization=incluit -Dsonar.sources=. -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectBaseDir=../src -Dproject.home=../src -Dsonar.login=b4374702344cc6949ebbbafcad6b4ea1d002ba1d'
        - docker ps
        - docker images
        - docker system prune -a -f

    - stage: Validation
      script:
        - echo 'The Pipeline was validated!!!!'
