language: node_js
node_js:
  - "14"
dist: xenial
sudo: false
addons:
  chrome: stable
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn run lint
script: yarn run $COMMAND
matrix:
  include:
    - env: COMMAND=test
    - env: COMMAND=test:leak
    - env: COMMAND=benchmark:bundlesize
branches:
  only:
    - master
cache:
  yarn: true