dist: bionic
language: rust

branches:
  except:
    - stable

matrix:
  fast_finish: true
  include:
    - os: linux
      rust: stable

    - os: linux
      rust: nightly

    # minimum supported version
    - os: linux
      rust: 1.42.0

    - os: osx
      rust: stable

env:
  global:
    - RUST_BACKTRACE=1

script:
  - bash ./scripts/travis.sh
