version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

install:
- ps: >-
    cd src

    nuget restore Vortice.Windows.sln

    $env:VORTICE_BUILD_NUMBER = ([int]$env:APPVEYOR_BUILD_NUMBER).ToString("000")
   
    $env:VORTICE_VERSION_SUFFIX = "pre$env:VORTICE_BUILD_NUMBER"

    $env:appveyor_nuget_push = 'false'

    if(-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      if($env:appveyor_repo_tag -eq 'True') {
    	  if($env:appveyor_repo_tag_name -match '^v[0-9]') {
           $env:appveyor_nuget_push = 'true'
           $env:VORTICE_VERSION_SUFFIX = ""
        }
    	  if($env:appveyor_repo_tag_name -eq 'latest') {
           $env:appveyor_nuget_push = 'true'
        }        
      }
    }

build:
  project: src/Vortice.Windows.sln
  verbosity: minimal

before_package:
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release Vortice.Runtime.COM/Vortice.Runtime.COM.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release Vortice.DirectX/Vortice.DirectX.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release Vortice.DXGI/Vortice.DXGI.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release Vortice.Direct3D11/Vortice.Direct3D11.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release Vortice.Direct3D12/Vortice.Direct3D12.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release Vortice.Direct2D1/Vortice.Direct2D1.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release Vortice.D3DCompiler/Vortice.D3DCompiler.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release Vortice.XInput/Vortice.XInput.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release Vortice.Dxc/Vortice.Dxc.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release Vortice.Multimedia/Vortice.Multimedia.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release Vortice.XAudio2/Vortice.XAudio2.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release Vortice.X3DAudio/Vortice.X3DAudio.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release Vortice.Direct3D9/Vortice.Direct3D9.csproj
  
artifacts:
- path: bin\Release\Packages\*.nupkg
  name: Nugets Artifacts

nuget:
  project_feed: true

deploy:
- provider: NuGet
  api_key:
    secure: 7kKL2l4dDfYB1nulVfUJYAtx43lETKMX+fMrnOwO9wljBNXanlMubrTSjgpaWnzn
  on:
    appveyor_nuget_push: true
  artifact: Nugets Artifacts 
  
