platform:
  - x64

environment:
  matrix:
    - RUST_VERSION: stable
      PLATFORM_TARGET: x86_64
      PLATFORM_VS: x64

install:
  # Install Rust.
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -yv --default-toolchain %RUST_VERSION% --default-host x86_64-pc-windows-msvc
  - set PATH=%USERPROFILE%\.cargo\bin;%PATH%
  - rustc -vV
  - cargo -vV

build_script:
  - cargo build --all-features -p sailfish -p sailfish-compiler

test_script:
  - cargo test --all-features -p sailfish -p sailfish-compiler -p integration-tests

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
