branches:
  only:
    - master

environment:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma2 -mx=9
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build_script:
  - gradlew.bat assemble testClasses --no-daemon --stacktrace

test_script:
  - gradlew.bat check --no-daemon --stacktrace

on_success:
  - ps: rm C:\Users\appveyor\.gradle\caches\modules-2\modules-2.lock -force
  - ps: rm C:\Users\appveyor\.gradle\caches\*\plugin-resolution\ -recurse -force
  - ps: rm C:\Users\appveyor\.gradle\caches\*\fileHashes\fileHashes.bin -force
  - ps: rm C:\Users\appveyor\.gradle\caches\*\fileHashes\fileHashes.lock -force

cache:
  - C:\Users\appveyor\.gradle
