name: Node CI

on: [push]

jobs: 
  lint:
    runs-on: [ubuntu-latest]
    steps:
    - name: print-OS
      run: lsb_release -a
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install
      run: |
        yarn install --frozen-lockfile
        yarn lint

  test:
    runs-on: [ubuntu-16.04]
    strategy:
      matrix:
        cypress-version: ["current", 3.4.1]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install
      run: |
        yarn install --frozen-lockfile
        [[ ${{ matrix.cypress-version }} == 'current' ]] || yarn add -D cypress@${{ matrix.cypress-version }}
        yarn test
        yarn test-e2e
      env:
        CI: true
  deploy:
    runs-on: [ubuntu-latest]
    needs: [test, lint]
    steps:
      - uses: actions/checkout@master

      - uses: codfish/semantic-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: |
          echo $RELEASE_VERSION
          echo $RELEASE_MAJOR
          echo $RELEASE_MINOR
          echo $RELEASE_PATCH
     
