name: Android CI

on:
  pull_request:
    branches:
      - master

jobs:
  ktlint:
    name: Kotlin Linter
    runs-on: ubuntu-latest

    steps:
       - name: "checkout"
         uses: actions/checkout@v2

       - name: "ktlint"
         uses: "vroy/gha-kotlin-linter@v1"

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        ./gradlew assembleDebug
        ./gradlew testGoogleDebugUnitTest --stacktrace

  fdroid:
    name: F-droid build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build for F-Droid
        run: |
          ./gradlew assembleFossDebug
