name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Update
      run: sudo apt-get update

    - name: Install lcov
      run: sudo apt-get install lcov

    - name: Install OpenGL dev
      run: sudo apt-get install xorg-dev libglu1-mesa-dev mesa-common-dev

    - name: Install ALSA dev
      run: sudo apt-get install libasound2-dev

    - name: Install PulseAudio dev
      run: sudo apt-get install libpulse-dev

    - name: Install Python dev
      run: sudo apt-get install python3.7-dev

    - name: Build Third Party Dependencies
      run: >
        mkdir build &&
        cd build &&
        export PATH=$PATH:$PWD/DJV-install-Debug/bin &&
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/DJV-install-Debug/lib &&
        export PYTHONPATH=$PWD/DJV-install-Debug/lib:$PYTHONPATH &&
        mkdir DJV-third-party-Debug &&
        cd DJV-third-party-Debug &&
        cmake ../../third-party -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../DJV-install-Debug -DDJV_THIRD_PARTY_OPTIONAL=FALSE -DDJV_PYTHON=FALSE -DDJV_OPENGL_ES2=TRUE &&
        cmake --build . &&
        cmake --build . --target install

    - name: Build DJV
      run: >
        cd build &&
        export PATH=$PATH:$PWD/DJV-install-Debug/bin &&
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/DJV-install-Debug/lib &&
        export PYTHONPATH=$PWD/DJV-install-Debug/lib:$PYTHONPATH &&
        mkdir DJV-Debug &&
        cd DJV-Debug &&
        cmake ../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../DJV-install-Debug -DCMAKE_PREFIX_PATH=../DJV-install-Debug -DDJV_THIRD_PARTY_OPTIONAL=FALSE -DDJV_BUILD_TINY=TRUE -DDJV_GCOV=TRUE -DDJV_PYTHON=FALSE -DDJV_OPENGL_ES2=TRUE &&
        cmake --build .

    - name: Run tests
      run: >
        cd build &&
        export PATH=$PATH:$PWD/DJV-install-Debug/bin &&
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/DJV-install-Debug/lib &&
        export PYTHONPATH=$PWD/DJV-install-Debug/lib:$PYTHONPATH &&
        cd DJV-Debug &&
        make test

