name: "Validate Gradle Wrapper"

on:
  push:
    branches:
      - main
      - orbit/main
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - orbit/main

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
