name: CI

on: ["push", "pull_request"]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, windows-latest, ubuntu-18.04]
        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js 12.x
                uses: actions/setup-node@v1
                with:
                    node-version: 12.x

            -   name: Build
                run: |
                    npm ci
                    npm run electron:build
