name: Go
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "logo.png"
      - "docs/**"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "logo.png"
      - "docs/**"
      - "go.mod"
      - "go.sum"

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - run: go build -o gbc ./cmd/