name: "Linting"

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - 'master'

jobs:
  lint:
    name: Lint
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - shell: bash -l {0}
        run: |
          npm install
          npm check
          npm build
