name: Crossroad

on: [push]

jobs:
  iOS:
    runs-on: macos
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        DESTINATION="platform=iOS Simulator,name=iPhone 8" SCHEME="Crossroad-iOS"
        xcodebuild test -project Crossroad.xcodeproj -scheme "${SCHEME}" -destination "${DESTINATION}"
  tvOS:
    runs-on: macos
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        DESTINATION="platform=tvOS Simulator,name=Apple TV 4K" SCHEME="Crossroad-tvOS"
        xcodebuild test -project Crossroad.xcodeproj -scheme "${SCHEME}" -destination "${DESTINATION}"
  Lint:
    runs-on: macos
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        gem install cocoapods
        pod repo update
        brew install swiftlint
    - name: SwiftLint
      run: swiftlint --strict
    - name: CocoaPods
      run: pod lib lint --allow-warnings
