name: CI

on: ["push", "pull_request"]

env:
    CI: true

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js 12.x
                uses: actions/setup-node@v1
                with:
                    node-version: 12.x

            -   uses: microsoft/playwright-github-action@v1
            -   name: Install dependencies
                run: npm ci

            -   name: Lint
                run: npm run lint

            -   name: Build
                run: npm run build

            -   name: Test
                run: npm run test
