name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'As no action on the issue was taken, bot closes issue.'
        stale-pr-message: 'As no action on the PR was taken, bot closes PR.'
        stale-issue-label: 'no-activity'
        stale-pr-label: 'no-pr-activity'
