name: CI

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    
jobs:
  build:

    runs-on: windows-2016
    
    steps:
    - name: Clone Code
      uses: actions/checkout@v1
    
    - name: Setup Visual Studio Command Prompt
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Build
      run: |
        msbuild /restore /t:Build XamarinFormsControls.sln /p:Configuration=Release

    - name: Upload artfacts
      uses: actions/upload-artifact@v1
      with:
        name: NuGet Packages
        path: artifacts/Release/NuGet
      
