name: Garbage collect

on:
  schedule:
    - cron: '0 0 * * 0,3'

env:
  BINTRAY_ORG: fullstaq

jobs:
  clean_repos:
    name: Clean APT/YUM repos
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: ./internal-scripts/ci-cd/garbage-collect/list-repos.sh
        env:
          BINTRAY_API_USERNAME: ${{ secrets.BINTRAY_API_USERNAME }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
      - run: ./internal-scripts/ci-cd/garbage-collect/clean-repos.sh
        env:
          BINTRAY_API_USERNAME: ${{ secrets.BINTRAY_API_USERNAME }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
